In [2]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

## Задание 1: Реализовать скалярное произведение двух векторов
Пользоваться стандартными функциями для прямого вычисления нельзя.
Менять тип переменных a и b нельзя

In [3]:
a = list(np.random.rand(15))
b = list(np.random.rand(15))

In [4]:
def scalar_product(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i]*b[i]
    return result

In [5]:
# Сравнение с функцией dot из numpy.
print(scalar_product(a, b))
print(np.dot(a,b))


2.994777892154492
2.994777892154492


# Задание 2: Реализовать матричное произведение
Пользоваться стандартными функциями для прямого вычисления нельзя.
Можете воспользоваться своей релизацией функции scalar_product.
Менять тип переменных A и B нельзя

In [6]:
A = list(np.random.rand(5, 12))
B = list(np.random.rand(12, 7))

In [7]:
def matrix_product(A, B):
    matrix_prod = list(np.zeros((len(A), len(B[0]))))

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                matrix_prod[i][j] += A[i][k] * B[k][j]

    return matrix_prod
print(matrix_product(A,B))

[array([3.22518733, 3.07531451, 1.66177003, 1.91922347, 3.0159208 ,
       2.70529206, 2.88937917]), array([2.59385055, 1.96547847, 1.02082029, 1.28283726, 1.70445133,
       2.24343247, 1.77258964]), array([4.20496226, 2.98330102, 2.07821707, 2.31139164, 3.17475311,
       3.7288389 , 3.28258558]), array([4.50232737, 2.8446842 , 2.0331876 , 2.49272866, 3.06954875,
       3.61047788, 3.03058964]), array([3.21133454, 2.99260759, 1.42593392, 2.18538063, 2.92921023,
       2.24984516, 2.61871923])]


In [8]:
# Сравнение с функцией dot из numpy.
print(np.array(matrix_product(A, B)) - np.dot(A, B))


[[ 0.00000000e+00 -4.44089210e-16  0.00000000e+00  0.00000000e+00
  -4.44089210e-16  0.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -4.44089210e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  4.44089210e-16  0.00000000e+00]
 [ 0.00000000e+00  4.44089210e-16  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.44089210e-16  0.00000000e+00  2.22044605e-16  0.00000000e+00
  -4.44089210e-16  4.44089210e-16  0.00000000e+00]]


## Задание 3: собственная реализация PCA
пользоваться можно только функциями из numpy

In [9]:
a = np.array([[1,3,2], [5,9,7]])
a

array([[1, 3, 2],
       [5, 9, 7]])

In [10]:
v = np.array([1,7,3,2,4])
sort_ind = np.argsort(v)
v[sort_ind]

array([1, 2, 3, 4, 7])

In [11]:
import numpy as np

class SimplePCA:
    def __init__(self, n_components):
        self.n_components = n_components

    def fit(self, X):
        # Нормализация
        self.X_mean = X.mean(axis=0)
        self.X_std = X.std(axis=0)
        X_normalized = (X - X.mean(axis=0)) / X.std(axis=0)
        

        # Вычисление ковариационной матрицы
        cov_x = np.cov(X_normalized.T)
        print(cov_x.shape)

        # Вычисление собственных значений и собственных векторов
        eigenvalues, eigenvectors = np.linalg.eig(cov_x)

        # Сортировка собственных векторов по убыванию собственных значений
        sorted_vector = eigenvectors[:, np.argsort(eigenvalues)[::-1]]
        print(eigenvalues[ np.argsort(eigenvalues, axis=-1)[::-1]])

        # Выбираем первые n_components собственных векторов
        self.sorted_vectors = sorted_vector[:, :self.n_components]


    def transform(self, X):
        # Ваш код
        X_normalized = (X - self.X_mean) / self.X_std
        return np.dot(X_normalized, self.sorted_vectors)

X, _ = make_blobs(n_samples=100, n_features=3, centers=1, random_state=0)

pca = SimplePCA(n_components=2)
pca.fit(X)
X_pca = pca.transform(X)

print("Первые 5 элементов после применения PCA:\n", X_pca[:5])

(3, 3)
[1.25356499 1.0119259  0.76481215]
Первые 5 элементов после применения PCA:
 [[ 0.14906228 -0.23866011]
 [-2.30503449 -0.21426715]
 [-0.48126702 -0.64756423]
 [-1.39731755  2.06441233]
 [ 2.26940507 -0.9035159 ]]


In [12]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
X, _ = make_blobs(n_samples=100, n_features=3, centers=1, random_state=0)
scaler = StandardScaler()
X_ = scaler.fit_transform(X)

pca_sklearn = PCA(n_components=2)
X_pca_sklearn = pca_sklearn.fit_transform(scaler.fit_transform(X))

print("Первые 5 элементов после применения PCA из sklearn:\n", X_pca_sklearn[:5])


Первые 5 элементов после применения PCA из sklearn:
 [[ 0.14906228  0.23866011]
 [-2.30503449  0.21426715]
 [-0.48126702  0.64756423]
 [-1.39731755 -2.06441233]
 [ 2.26940507  0.9035159 ]]
